title: Today I Learned
author: learnedToday
description: A series of notes and learnings journaled for purposes of self-improvement.
baseurl: /

#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
# A series of notes and learnings journaled for purposes of self-improvement. 
# Thoughts mostly around Kotlin, Android, Mobile Applications and Software 
# Design.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AndroidDev
github_username:  learnedtoday

navbar-links:
  About Me: "about"

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"

# Build settings
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-gist
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
  - CNAME  
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      readtime: true

jekyll_compose:
    auto_open: true
